on:
  push:
    branches:
      - "main"
    paths:
      - "buildSrc/build.gradle.kts"
      - "buildSrc/src/main/kotlin/*.kt"
      - "buildSrc/src/main/kotlin/*.gradle.kts"
      - "src/main/java/**/*.java"
      - "src/main/resources/"
      - "!.editorconfig"
      - "!.gitattributes"
      - "!.gitignore"
      - "!CONTRIBUTING.md"
      - "!LICENSE"
      - "!README"
      - "!README.md"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"
  pull_request:
    branches:
      - "main"
    paths:
      - "buildSrc/build.gradle.kts"
      - "buildSrc/src/main/kotlin/*.kt"
      - "buildSrc/src/main/kotlin/*.gradle.kts"
      - "src/main/java/**/*.java"
      - "src/main/resources/"
      - "!.editorconfig"
      - "!.gitattributes"
      - "!.gitignore"
      - "!CONTRIBUTING.md"
      - "!LICENSE"
      - "!README"
      - "!README.md"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - minecraft_version: 26.1
            modmenu_version: 18.0.0-alpha.7
          - minecraft_version: 26.1.1
            modmenu_version: 18.0.0-alpha.7
          - minecraft_version: 26.1.2
            modmenu_version: 18.0.0-alpha.7

    name: Build (${{ matrix.minecraft_version }})
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: corretto
          cache: gradle

      - uses: gradle/actions/setup-gradle@v6

      - run: ./gradlew build -Pminecraft_version=${{ matrix.minecraft_version }} -Pmodmenu_version=${{ matrix.modmenu_version }}

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ github.run_id }}
          path: |
            ./build/libs/*.jar
          retention-days: 3
          overwrite: true
